<a href="https://colab.research.google.com/github/EdCarlosBicudo/microdados_enem_2019/blob/main/notebooks/1_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importação da biblioteca Pandas

In [1]:
import pandas as pd

Montando o dietório do Google Drive para acessar os dados

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Lendo os dados e dando uma olhada inicial

In [18]:
dados = pd.read_csv("/content/drive/MyDrive/dados/microdados_1.csv", sep=";", encoding ='latin1')

In [19]:
dados.shape

(95271, 136)

In [20]:
dados.head()

   NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA  ... Q023  Q024 Q025
0  190005611542    2019                  2611606  ...    A     A    B
1  190005467499    2019                  1100122  ...    A     A    A
2  190005805023    2019                  3550308  ...    A     C    B
3  190006071487    2019                  3303500  ...    B     B    B
4  190005926252    2019                  4113700  ...    A     B    B

[5 rows x 136 columns]

Removendo registros onde o instrito não compareceu a nenhuma prova.

In [21]:
dados = dados.drop(dados[(dados['TP_PRESENCA_CN'] == 0) & 
                         (dados['TP_PRESENCA_CH'] == 0) & 
                         (dados['TP_PRESENCA_LC'] == 0) & 
                         (dados['TP_PRESENCA_MT'] == 0)].index)

In [22]:
dados.head()

   NU_INSCRICAO  NU_ANO  CO_MUNICIPIO_RESIDENCIA  ... Q023  Q024 Q025
0  190005611542    2019                  2611606  ...    A     A    B
1  190005467499    2019                  1100122  ...    A     A    A
2  190005805023    2019                  3550308  ...    A     C    B
3  190006071487    2019                  3303500  ...    B     B    B
4  190005926252    2019                  4113700  ...    A     B    B

[5 rows x 136 columns]

In [23]:
dados.shape

(59215, 136)

O objetivo do projeto é analizar se e como algumas características afetam as notas dos alunos.

As colunas que não foram consideradas necessárias foram retiradas.

In [24]:
colunas_para_dropar = ['NU_INSCRICAO', 'NU_ANO', 'CO_MUNICIPIO_RESIDENCIA', 'CO_UF_RESIDENCIA', 'CO_MUNICIPIO_NASCIMENTO', 
                       'CO_UF_NASCIMENTO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC', 'CO_UF_ESC', 'IN_SEM_RECURSO', 'IN_BRAILLE', 
                       'IN_AMPLIADA_24', 'IN_AMPLIADA_18', 'IN_LEDOR','IN_ACESSO', 'IN_TRANSCRICAO', 'IN_LIBRAS', 
                       'IN_TEMPO_ADICIONAL', 'IN_LEITURA_LABIAL', 'IN_MESA_CADEIRA_RODAS', 'IN_MESA_CADEIRA_SEPARADA',
                       'IN_APOIO_PERNA', 'IN_GUIA_INTERPRETE', 'IN_COMPUTADOR', 'IN_CADEIRA_ESPECIAL', 'IN_CADEIRA_CANHOTO', 
                       'IN_CADEIRA_ACOLCHOADA', 'IN_PROVA_DEITADO', 'IN_MOBILIARIO_OBESO', 'IN_LAMINA_OVERLAY', 
                       'IN_PROTETOR_AURICULAR', 'IN_MEDIDOR_GLICOSE', 'IN_MAQUINA_BRAILE', 'IN_SOROBAN', 'IN_MARCA_PASSO', 
                       'IN_SONDA', 'IN_MEDICAMENTOS', 'IN_SALA_INDIVIDUAL', 'IN_SALA_ESPECIAL', 'IN_SALA_ACOMPANHANTE',
                       'IN_MOBILIARIO_ESPECIFICO', 'IN_MATERIAL_ESPECIFICO', 'IN_NOME_SOCIAL', 'CO_MUNICIPIO_PROVA', 
                       'CO_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN', 
                       'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 
                       'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT'
]

In [25]:
dados.drop(colunas_para_dropar, axis=1, inplace=True)

In [26]:
dados.shape

(59215, 74)

Renomeando as colunas para facilitar o entendimento dos dados

In [27]:
novas_colunas = {'NO_MUNICIPIO_RESIDENCIA': 'MUNICIPIOR ESISDENCIA', 'SG_UF_RESIDENCIA': 'UF RESIDENCIA',
                'NU_IDADE': 'IDADE', 'TP_SEXO': 'SEXO',
                 'TP_ESTADO_CIVIL': 'ESTADO CIVIL', 'TP_COR_RACA': 'COR',
                'TP_NACIONALIDADE': 'NACIONALIDADE', 'NO_MUNICIPIO_NASCIMENTO': 'MUNICIPIO NASCIMENTO',
                'SG_UF_NASCIMENTO': 'UF NASCIMENTO', 'TP_ST_CONCLUSAO': 'CONCLUSAO ENSINO MEDIO',
                'TP_ANO_CONCLUIU': 'ANO CONCLUSAO ENSINO MEDIO', 'TP_ESCOLA': 'TIPO ESCOLA',
                'TP_ENSINO': 'TIPO ENSINO', 'IN_TREINEIRO': 'TREINAR',
                'NO_MUNICIPIO_ESC': 'MUNICIPIO ESCOLA', 'SG_UF_ESC': 'UF ESCOLA',
                'TP_DEPENDENCIA_ADM_ESC': 'DEPENDENCIA ADMINISTRATIVA', 'TP_LOCALIZACAO_ESC': 'LOCALIZACAO ESCOLA',
                'TP_SIT_FUNC_ESC': 'SITUCACAO ESCOLA', 'IN_BAIXA_VISAO': 'BAIXA VISAO',
                'IN_CEGUEIRA': 'CEGUEIRA', 'IN_SURDEZ': 'SURDEZ',
                'IN_DEFICIENCIA_AUDITIVA': 'DEFICIENCIA AUDITIVA', 'IN_SURDO_CEGUEIRA': 'SURDO CEGO',
                'IN_DEFICIENCIA_FISICA': 'DEFICIENCIA FISICA', 'IN_DEFICIENCIA_MENTAL': 'DEFICIENCIA MENTAL',
                'IN_DEFICIT_ATENCAO': 'DEFICT DE ATENCAO', 'IN_DISLEXIA': 'DISLEXIA',
                'IN_DISCALCULIA': 'DISCALCULIA', 'IN_AUTISMO': 'AUTISMO',
                'IN_VISAO_MONOCULAR': 'VISAO MONOCULAR', 'IN_OUTRA_DEF': 'OUTRA DEFICIENCIA',
                'IN_GESTANTE': 'GESTANTE', 'IN_LACTANTE': 'LACTANTE',
                'IN_IDOSO': 'IDOSO', 'IN_ESTUDA_CLASSE_HOSPITALAR': 'ENTUDA CLASSE HOSPITALAR',
                'NO_MUNICIPIO_PROVA': 'MINICIPIO PROVA', 'SG_UF_PROVA': 'UF PROVA',
                'NU_NOTA_CN': 'NOTA CIENCIAS DA NATUREZA', 'NU_NOTA_CH': 'NOTA CIENCIAS HUMANAS',
                'NU_NOTA_LC': 'NOTA LINGUAGENS E CODIGOS', 'NU_NOTA_MT': 'NOTA MATEMATICA',
                'TP_STATUS_REDACAO': 'SITUACAO DAREDACAO', 'NU_NOTA_COMP1': 'NOTA COMPETENCIA 1',
                'NU_NOTA_COMP2': 'NOTA COMPETENCIA 2', 'NU_NOTA_COMP3': 'NOTA COMPETENCIA 3',
                'NU_NOTA_COMP4': 'NOTA COMPETENCIA 4', 'NU_NOTA_COMP5': 'NOTA COMPETENCIA 5',
                'NU_NOTA_REDACAO': 'NOTA REDACAO', 'Q001': 'SERIE ESTUDO PAI',
                'Q002': 'SERIE ESTUDO MAE', 'Q003': 'OCUPACAO PAI',
                'Q004': 'OCUPACAO MAE', 'Q005': 'MORADORES NA RESIDENCIA',
                'Q006': 'RENDA FAMILIAR', 'Q007': 'EMPREGADO DOMESTICO',
                'Q008': 'BANHEIRO', 'Q009': 'QUARTOS', 'Q010': 'CARRO',
                'Q011': 'MOTOCICLETA', 'Q012': 'GELADEIRA',
                'Q013': 'FREEZER', 'Q014': 'MAQUINA DE LAVAR',
                'Q015': 'MAQUINA DE SECAR', 'Q016': 'MICRO-ONDAS',
                'Q017': 'MAQUINA DE LAVAR LOUCA', 'Q018': 'ASPIRADOR DE PO',
                'Q019': 'TV COLORIDA', 'Q020': 'DVD',
                'Q021': 'TV POR ASSINATURA', 'Q022': 'TELEFONE CELULAR',
                'Q023': 'TELEFONE FIXO', 'Q024': 'COMPUTADOR',
                'Q025': 'INTERNET',}

In [28]:
dados.rename(columns=novas_colunas, inplace=True)

In [29]:
dados.head()

  MUNICIPIOR ESISDENCIA UF RESIDENCIA  IDADE  ... TELEFONE FIXO  COMPUTADOR  INTERNET
0                Recife            PE     22  ...             A           A         B
1             Ji-Paraná            RO     17  ...             A           A         A
2             São Paulo            SP     18  ...             A           C         B
3           Nova Iguaçu            RJ     16  ...             B           B         B
4              Londrina            PR     41  ...             A           B         B

[5 rows x 74 columns]

O Enem conta com cinco notas em diferentes matérias: Ciências da Natureza, Ciências Humanas, Linguagens e Códigos, Matemática e Redação.

Essas notas podem ser utilizadas de maneiras diferentes e com pesos diferentes por cada instituição de ensino superior.

Aqui será utlizado como nota final a média simples dessas cinco notas.

In [30]:
#Subistituindo notas faltantes por 0
dados['NOTA CIENCIAS DA NATUREZA'] = dados['NOTA CIENCIAS DA NATUREZA'].fillna(0)
dados['NOTA CIENCIAS HUMANAS'] = dados['NOTA CIENCIAS HUMANAS'].fillna(0)
dados['NOTA LINGUAGENS E CODIGOS'] = dados['NOTA LINGUAGENS E CODIGOS'].fillna(0)
dados['NOTA MATEMATICA'] = dados['NOTA MATEMATICA'].fillna(0)
dados['NOTA REDACAO'] = dados['NOTA REDACAO'].fillna(0)

In [31]:
dados['MEDIA FINAL'] = ((dados['NOTA CIENCIAS DA NATUREZA'] + dados['NOTA CIENCIAS HUMANAS'] + 
                         dados['NOTA LINGUAGENS E CODIGOS'] + dados['NOTA MATEMATICA'] + 
                         dados['NOTA REDACAO'])/5)

Salvando os dados

In [32]:
dados.to_csv('dados_limpos_1.csv', sep=';')